version: "3.3"
services:
  web:
    build: .
    networks:
      - default
    ports:
      - "3000:3000"
      - "1080:1080"
    volumes:
      - .:/var/www/html
    command: dockerup
    depends_on:
      - db
  db:
    image: mysql:latest
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: guest
